import { type PLAYER } from '@/types/database/models'

export const players: PLAYER[] = [
  { name: 'Reginald Ahenkorah- Marfo', id: '1', rating: 1280 },
  { name: 'Amoani Charles Antwi', id: '2', rating: 1419 },
  { name: 'Luqman Abubakar', id: 'luqman1771', rating: 1381 },
  { name: 'Kofi Amoah Barimah', id: '4', rating: 1362 },
  { name: 'Precious Paulina Adjei', id: '5', rating: 1284 },
  { name: 'Antonio Bossor Yankey', id: '6', rating: 1381 },
  { name: 'Minenhle Peace Tsabedze', id: '7', rating: 1222 },
  { name: 'Akwasi Poku Ofori Agyei', id: '8', rating: 1442 },
  { name: 'Melody Chahanda', id: '9', rating: 1319 },
  { name: 'Alswell Matizigah', id: '10', rating: 1343 },
  { name: 'Bannor Seth Tetteh', id: '11', rating: 1202 },
  { name: 'Opoku Fredrick Nana Yaw', id: '12', rating: 1302 },
  { name: 'Regis Lamboni', id: '13', rating: 1322 },
  { name: 'Nkrumah Job Adjei', id: '14', rating: 1340 },
  { name: 'Emmanuel Frimpong Yeboah', id: '15', rating: 1364 },
  { name: 'Ayesu George', id: '16', rating: 1377 },
  { name: 'Joshua Gbegah', id: '17', rating: 1361 },
  { name: 'Nana Kwame Yeboah Opoku', id: '18', rating: 1282 },
  { name: 'Koomsom Isaac', id: '19', rating: 1325 },
  { name: 'Franscis Antwi', id: '20', rating: 1440 },
  { name: 'Daniel Kanor Attiapah', id: '21', rating: 1362 },
  { name: 'Solomon Asemsuro', id: '22', rating: 1418 },
  { name: 'Wilfred Dwamena Abrah', id: '23', rating: 1344 },
  { name: 'Ansah Ekow Joel', id: '24', rating: 1341 },
  { name: 'Jubilee Roxanne Bleboo', id: '25', rating: 1318 },
  { name: 'Odoi Herbert Martey', id: '26', rating: 1340 },
  { name: 'Bye', id: '27', rating: 1400 },
  { name: 'Humphrey', id: '27', rating: 2550 },
  { name: 'Alexis', id: '28', rating: 1720 },
  { name: 'Matthew', id: '29', rating: 1423 },
  { name: 'Daniel', id: '30', rating: 1460 },
]
