import { type PLAYER } from '@/types/database/models'

export const players: PLAYER[] = [
  { id: 'sixelA23', name: 'Alexis Baffour Owusu Annor', rating: 1560 },
  { id: 'sisco_fy', name: 'Emmanuel Yeboah', rating: 1380 },
  { id: 'PaapaFahodzi', name: 'Paapa Fahodzi', rating: 1383 },
  { id: 'Nenyo', name: 'Enoch Nenyo', rating: 1428 },
  { id: 'Marfo1', name: 'Francis Marfo', rating: 1450 },
  { id: 'Kabywabtoms', name: 'Kofi Amoh Barimah', rating: 1505 },
  { id: 'macLean51', name: 'Michael Anim Danso', rating: 0 },
  { id: 'j3akoblaechess', name: 'Johnny Edem Agboado', rating: 1409 },
  { id: 'Survivor_15', name: 'Joshua Kumordzie Gbegah', rating: 1338 },
  { id: 'AY112', name: 'Akwasi Yeboah', rating: 1348 },
  { id: 'Raph_k', name: 'Raphael Appiah', rating: 1383 },
  { id: 'teslamate', name: 'Nana Kwame Opoku', rating: 1237 },
  { id: 'asemsuros', name: 'Solomon Asemsuro', rating: 1423 },
  { id: 'Mr-Hydrogen', name: 'Ernest Adokwei Tetteh', rating: 1329 },
  { id: 'Sossah', name: 'Enam Tsike-Sossah', rating: 1391 },
  { id: 'Anane_Carter', name: 'Job Adjei Nkrumah', rating: 1340 },
  { id: 'ii_apoa', name: 'Akwasi Agyei', rating: 1457 },
  { id: 'qroxie', name: 'Jubilee Bleboo', rating: 1310 },
  { id: 'Yuritarded1234', name: 'Stan Badu', rating: 1455 },
  { id: 'Reg_is', name: 'Regis Lamboni', rating: 1362 },
  { id: 'charlesa11[chess.com]', name: 'Charles Amoani', rating: 1499 },
  { id: 'Jjk2233', name: 'Kwadwo Acheampong', rating: 1406 },
  { id: 'ikoomsonn', name: 'Isaac Koomson', rating: 1325 },
  { id: 'Kealfx', name: 'Eleazar Adams', rating: 850 },
  { id: 'Lobeng', name: 'Lawrence Obeng', rating: 1400 },
  { id: 'EdemEthics', name: 'Johnny Edem Agboado', rating: 1400 },
  { id: 'Bossgrass', name: 'David Broni', rating: 0 },
  { id: 'frick_0', name: 'Fredrick Opoku', rating: 1285 },
]
