import { type PLAYER } from '@/types/database/models'

export const players: PLAYER[] = [
  {
    first_name: 'Alexis',
    last_name: 'Baffour Owusu Annor',
    sex: 'male',
    dob: new Date('2003-11-05'),
    programme: 'Pharmacy',
    username: 'sixelA23',
    rating: 1560,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Emmanuel',
    last_name: 'Yeboah',
    sex: 'male',
    dob: new Date('2005-07-20'),
    programme: 'Computer Science',
    username: 'sisco_fy',
    rating: 1380,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Paapa',
    last_name: 'Fahodzi',
    sex: 'male',
    dob: new Date('2002-10-03'),
    programme: 'Medicine',
    username: 'PaapaFahodzi',
    rating: 1383,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Enoch',
    last_name: 'Nenyo',
    sex: 'male',
    dob: new Date('2007-11-25'),
    programme: 'Telecom Engineering',
    username: 'Nenyo',
    rating: 1428,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Francis',
    last_name: 'Marfo',
    sex: 'male',
    dob: new Date('2003-03-06'),
    programme: 'Bsc Business Administration Accounting',
    username: 'Marfo1',
    rating: 1450,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Kofi Amoh',
    last_name: 'Barimah',
    sex: 'male',
    dob: new Date('2005-04-01'),
    programme: 'BSc. Marine Engineering',
    username: 'Kabywabtoms',
    rating: 1505,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Michael',
    last_name: 'Anim Danso',
    sex: 'male',
    dob: new Date('2002-09-21'),
    programme: 'None',
    username: 'macLean51',
    rating: 0,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Johnny Edem',
    last_name: 'Agboado',
    sex: 'male',
    dob: new Date('1999-08-24'),
    programme: 'None',
    username: 'j3akoblaechess',
    rating: 1409,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Joshua',
    last_name: 'Kumordzie Gbegah',
    sex: 'male',
    dob: new Date('2006-01-15'),
    programme: 'BSc Chemical Engineering',
    username: 'Survivor_15',
    rating: 1338,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Akwasi',
    last_name: 'Yeboah',
    sex: 'male',
    dob: new Date('2000-02-13'),
    programme: 'MPhil Soil & Water Engineering',
    username: 'AY112',
    rating: 1348,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Raphael',
    last_name: 'Appiah',
    sex: 'male',
    dob: new Date('2003-05-26'),
    programme: 'Bsc. Biological sciences',
    username: 'Raph_k',
    rating: 1383,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Nana Kwame',
    last_name: 'Opoku',
    sex: 'male',
    dob: new Date('2005-09-17'),
    programme: 'Chemical engineering',
    username: 'teslamate',
    rating: 1237,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Solomon',
    last_name: 'Asemsuro',
    sex: 'male',
    dob: new Date('2004-05-10'),
    programme:
      'Bsc. Business Administration( Marketing and International Business )',
    username: 'asemsuros',
    rating: 1423,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Ernest',
    last_name: 'Adokwei Tetteh',
    sex: 'male',
    dob: new Date('2000-06-22'),
    programme: 'Molecular Medicine',
    username: 'Mr-Hydrogen',
    rating: 1329,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Enam',
    last_name: 'Tsike-Sossah',
    sex: 'male',
    dob: new Date('2005-09-08'),
    programme: 'Aerospace Engineering',
    username: 'Sossah',
    rating: 1391,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Job',
    last_name: 'Adjei Nkrumah',
    sex: 'male',
    dob: new Date('1992-06-24'),
    programme: 'None',
    username: 'Anane_Carter',
    rating: 1340,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Akwasi',
    last_name: 'Agyei',
    sex: 'male',
    dob: new Date('2005-03-20'),
    programme: 'Computer Science',
    username: 'ii_apoa',
    rating: 1457,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Jubilee',
    last_name: 'Bleboo',
    sex: 'female',
    dob: new Date('2005-10-19'),
    programme: 'Medicine',
    username: 'qroxie',
    rating: 1310,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Stan',
    last_name: 'Badu',
    sex: 'male',
    dob: new Date('2006-09-17'),
    programme: 'Computer Science',
    username: 'Yuritarded1234',
    rating: 1455,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Regis',
    last_name: 'Lamboni',
    sex: 'male',
    dob: new Date('2004-06-16'),
    programme: 'Medical imaging',
    username: 'Reg_is',
    rating: 1362,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Charles',
    last_name: 'Amoani',
    sex: 'male',
    dob: new Date('2005-11-11'),
    programme: 'Computer Engineering',
    username: 'charlesa11',
    rating: 1499,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Kwadwo',
    last_name: 'Acheampong',
    sex: 'male',
    dob: new Date('2003-12-01'),
    programme: 'Accounting',
    username: 'Jjk2233',
    rating: 1406,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Isaac',
    last_name: 'Koomson',
    sex: 'male',
    dob: new Date('2003-03-25'),
    programme: 'Electrical engineering',
    username: 'ikoomsonn',
    rating: 1325,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Enoch',
    last_name: 'Nenyo',
    sex: 'male',
    dob: new Date('2007-11-27'),
    programme: 'Telecom Engineering',
    username: 'Nenyo',
    rating: 1428,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Eleazar',
    last_name: 'Adams',
    sex: 'male',
    dob: new Date('2005-02-12'),
    programme: 'Mathematics',
    username: 'Kealfx',
    rating: 850,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Lawrence',
    last_name: 'Obeng',
    sex: 'male',
    dob: new Date('2006-12-19'),
    programme: 'Civil Engineering',
    username: 'Lobeng',
    rating: 1400,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Johnny Edem',
    last_name: 'Agboado',
    sex: 'male',
    dob: new Date('1999-08-24'),
    programme: 'None',
    username: 'EdemEthics',
    rating: 1400, // Original value was "1400+" in CSV
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'David',
    last_name: 'Broni',
    sex: 'male',
    dob: new Date('2005-11-19'),
    programme: 'Computer engineering',
    username: 'Bossgrass',
    rating: 0,
    club: 'KNUST CHESS CLUB',
  },
  {
    first_name: 'Fredrick',
    last_name: 'Opoku',
    sex: 'male',
    dob: new Date('2005-07-07'),
    programme: 'Mechanical Engineering',
    username: 'frick_0',
    rating: 1285,
    club: 'KNUST CHESS CLUB',
  },
]
