export const db = 'sicilian-main'
export const dbtest = 'sicilian-test'
export const gameCollection = 'games'
export const tournamentCollection = 'tournaments'
export const playerCollection = 'players'
export const clubCollection = 'clubs'
